dist: bionic

language: go

go:
  - 1.12.x

git:
  depth: 1

notifications:
  email: false

before_script:
  - go get -d -v github.com/go-sql-driver/mysql
  - go get -d -v github.com/gorilla/mux

script:
  - go build
